PermissionsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: PermissionsTable
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S

    KeySchema:
      - AttributeName: id
        KeyType: HASH

PermissionsTableIAM:
  Effect: Allow
  Action:
    - dynamodb:*
  Resource: 
    - ${self:custom.PermissionsTable.Arn}
