PoliciesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: PoliciesTable
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S

    KeySchema:
      - AttributeName: id
        KeyType: HASH

PoliciesTableIAM:
  Effect: Allow
  Action:
    - dynamodb:*
  Resource: 
    - ${self:custom.PoliciesTable.Arn}
