PolicyAssignmentsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: PolicyAssignmentsTable
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: entityId
        AttributeType: S
      - AttributeName: entityType
        AttributeType: S

    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: entityIdEntityTypeIndex
        KeySchema:
          - AttributeName: entityId
            KeyType: HASH
          - AttributeName: entityType
            KeyType: RANGE
        Projection:
          ProjectionType: ALL


PolicyAssignmentsTableIAM:
  Effect: Allow
  Action:
    - dynamodb:*
  Resource: 
    - ${self:custom.PolicyAssignmentsTable.Arn}
    - !Join ['/', ['${self:custom.PolicyAssignmentsTable.Arn}', 'index', '*']]
