RolesPermissionsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: RolesPermissionsTable
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: roleId
        AttributeType: S

    KeySchema:
      - AttributeName: id
        KeyType: HASH

    GlobalSecondaryIndexes:
      - IndexName: roleIdIndex
        KeySchema:
          - AttributeName: roleId
            KeyType: HASH
        Projection:
          ProjectionType: ALL
            

RolesPermissionsTableIAM:
  Effect: Allow
  Action:
    - dynamodb:*
  Resource: 
    - ${self:custom.RolesPermissionsTable.Arn}
    - !Join ['/', ['${self:custom.RolesPermissionsTable.Arn}', 'index', '*']]
