UsersTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: UsersTable
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S

      - AttributeName: email
        AttributeType: S

    KeySchema:
      - AttributeName: id
        KeyType: HASH

    GlobalSecondaryIndexes:
      - IndexName: emailIndex
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        Projection:
          ProjectionType: ALL
            
UsersTableIAM:
  Effect: Allow
  Action:
    - dynamodb:*
  Resource: 
    - ${self:custom.UsersTable.Arn}
    - !Join ['/', ['${self:custom.UsersTable.Arn}', 'index', '*']]
