service: auth-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  region: "eu-north-1"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: 
        - ${self:custom.UsersTable.Arn}
        - !Join ['/', ['${self:custom.UsersTable.Arn}', 'index', 'emailIndex']]

  environment:
    UsersTableName: ${self:custom.UsersTable.Name}
    StoresTableName: ${self:custom.StoresTable.Name}
    ProductsTableName: ${self:custom.ProductsTable.Name}


functions:
  auth:
    handler: src/handlers/auth.handler
    cors: true


  signup:
    handler: src/handlers/signup.handler
    events:
      - http:
          path: /signup
          method: post
          cors: true

  login:
    handler: src/handlers/login.handler
    events:
      - http:
          path: /login
          method: post
          cors: true

  delete_user:
    handler: src/handlers/delete_user.handler
    events:
      - http:
          path: /user/{id}/delete
          method: delete
          cors: true
          authorizer: auth


plugins:
  - serverless-python-requirements
  - serverless-api-gateway-caching


resources:
  Resources:
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: EXPIRED_TOKEN
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
    AuthFailureGatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
          
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UsersTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S

          - AttributeName: email
            AttributeType: S

        KeySchema:
          - AttributeName: id
            KeyType: HASH

        GlobalSecondaryIndexes:
          - IndexName: emailIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL

custom:
  UsersTable:
    Arn: !GetAtt UsersTable.Arn
    Name: !Ref UsersTable
  apiGatewayCaching:
    enabled: false
